// packages/ui-predicate-react/src/components/UIPredicateOptions.js
import React from 'react';
import PropTypes from 'prop-types';
import { useUIPredicateContext } from '../hooks';

export function UIPredicateOptions({ predicate }) {
  const {
    add,
    remove,
    isInAddCompoundMode,
    UITypes,
    getUIComponent,
  } = useUIPredicateContext();

  const AddComponent = getUIComponent(UITypes.PREDICATE_ADD);
  const RemoveComponent = getUIComponent(UITypes.PREDICATE_REMOVE);

  return (
    <div className="ui-predicate__options">
      <div className="ui-predicate__option">
        <RemoveComponent
          onClick={() => remove(predicate)}
          predicate={predicate}
          isInAddCompoundMode={isInAddCompoundMode}
          disabled={!predicate.$canBeRemoved}
        />
      </div>
      <div className="ui-predicate__option">
        <AddComponent
          predicate={predicate}
          isInAddCompoundMode={isInAddCompoundMode}
          onClick={() => add(predicate)}
        />
      </div>
    </div>
  );
}

UIPredicateOptions.propTypes = {
  predicate: PropTypes.object,
};

// packages/ui-predicate-vue3/src/ui-predicate-options.vue
<template>
  <div class="ui-predicate__options">
    <div class="ui-predicate__option">
      <component
        :is="getUIComponent(UITypes.PREDICATE_REMOVE)"
        :predicate="predicate"
        :disabled="predicate.$canBeRemoved === false"
        @click="remove(predicate)"
      />
    </div>
    <div class="ui-predicate__option">
      <component
        :is="getUIComponent(UITypes.PREDICATE_ADD)"
        :predicate="predicate"
        :is-in-add-compound-mode="isInAddCompoundMode"
        @click="add(predicate)"
      />
    </div>
  </div>
</template>

<script setup>
import { inject, computed } from "vue";

defineProps({
  predicate: {
    type: Object,
    required: true
  }
});

const remove = inject("remove");
const add = inject("add");
const getAddCompoundMode = inject("getAddCompoundMode");
const UITypes = inject("UITypes");
const getUIComponent = inject("getUIComponent");

const isInAddCompoundMode = computed(() => getAddCompoundMode());
</script>
