// packages/ui-predicate-react/src/components/UIPredicateComparisonArgument.js
import React from 'react';
import PropTypes from 'prop-types';
import { useUIPredicateContext } from '../hooks';

export function UIPredicateComparisonArgument({ predicate }) {
  const {
    getArgumentTypeComponentById,
    setArgumentValue,
  } = useUIPredicateContext();
  return React.createElement(
    getArgumentTypeComponentById(predicate.operator.argumentType_id),
    {
      predicate,
      value: predicate.argument,
      onChange(value) {
        setArgumentValue(predicate, value);
      },
    }
  );
}

UIPredicateComparisonArgument.propTypes = {
  predicate: PropTypes.object,
};

// packages/ui-predicate-vue3/src/ui-predicate-comparison-argument.vue
<template>
  <component
    :is="getArgumentTypeComponentById(predicate.operator.argumentType_id)"
    :value="predicate.argument"
    :predicate="predicate"
    @change="_setArgumentValue"
  />
</template>

<script>
export default {
  props: {
    predicate: {
      type: Object,
      required: true,
    },
  },
  inject: ["getArgumentTypeComponentById", "setArgumentValue"],
  methods: {
    _setArgumentValue(value) {
      this.setArgumentValue(this.predicate, value);
    },
  },
};
</script>
