// packages/ui-predicate-react/src/components/UIPredicateComparison.js
import React from 'react';
import PropTypes from 'prop-types';
import { useUIPredicateContext } from '../hooks';
import { UIPredicateComparisonArgument, UIPredicateOptions } from './';

export function UIPredicateComparison({ predicate, columns }) {
  const {
    setPredicateTarget_id,
    setPredicateOperator_id,
    UITypes,
    getUIComponent,
  } = useUIPredicateContext();

  const TargetsComponent = getUIComponent(UITypes.TARGETS);
  const OperatorsComponent = getUIComponent(UITypes.OPERATORS);

  return (
    <div className="ui-predicate__row ui-predicate__row--comparison">
      <div className="ui-predicate__col">
        <TargetsComponent
          columns={columns}
          predicate={predicate}
          onChange={target_id => setPredicateTarget_id(predicate, target_id)}
        />
      </div>
      <div className="ui-predicate__col">
        <OperatorsComponent
          columns={columns}
          predicate={predicate}
          onChange={operator_id =>
            setPredicateOperator_id(predicate, operator_id)
          }
        />
      </div>
      <div className="ui-predicate__col">
        <div className="ui-predicate__arguments">
          <UIPredicateComparisonArgument predicate={predicate} />
        </div>
      </div>
      <div className="ui-predicate__col">
        <UIPredicateOptions predicate={predicate} />
      </div>
    </div>
  );
}

UIPredicateComparison.propTypes = {
  predicate: PropTypes.object,
  columns: PropTypes.object,
};

// packages/ui-predicate-vue3/src/ui-predicate-comparison.vue
<template>
  <div class="ui-predicate__row ui-predicate__row--comparison">
    <div class="ui-predicate__col">
      <component
        :is="getUIComponent(UITypes.TARGETS)"
        class="ui-predicate__targets"
        :columns="columns"
        :predicate="predicate"
        @change="changeTarget($event)"
      />
    </div>
    <div class="ui-predicate__col">
      <component
        :is="getUIComponent(UITypes.OPERATORS)"
        class="ui-predicate__operators"
        :columns="columns"
        :predicate="predicate"
        @change="changeOperator($event)"
      />
    </div>
    <div class="ui-predicate__col">
      <ui-predicate-comparison-argument
        class="ui-predicate__arguments"
        :predicate="predicate"
      />
    </div>
    <div class="ui-predicate__col">
      <ui-predicate-options :predicate="predicate"></ui-predicate-options>
    </div>
  </div>
</template>

<script setup>
import { inject } from 'vue';

const props = defineProps({
  predicate: {
    type: Object,
    required: true,
  },
  columns: {
    type: Object,
    required: true,
  },
});

const add = inject('add');
const setPredicateTarget_id = inject('setPredicateTarget_id');
const setPredicateOperator_id = inject('setPredicateOperator_id');
const UITypes = inject('UITypes');
const getUIComponent = inject('getUIComponent');

const changeTarget = (target_id) => {
  setPredicateTarget_id(props.predicate, target_id);
};

const changeOperator = (operator_id) => {
  setPredicateOperator_id(props.predicate, operator_id);
};
</script>
