// packages/ui-predicate-react/src/ui-predicate-comparison-argument.js
import React, { Component } from 'react';

class UIPredicateComparisonArgument extends Component {
  render() {
    const {
      getArgumentTypeComponentById,
      setArgumentValue,
      predicate,
    } = this.props;
    const ArgumentComponent = getArgumentTypeComponentById(
      predicate.operator.argumentType_id
    );

    return (
      <ArgumentComponent
        {...this.props}
        value={predicate.argument}
        predicate={predicate}
        onChange={value => setArgumentValue(predicate, value)}
      />
    );
  }
}

export default UIPredicateComparisonArgument;

// packages/ui-predicate-vue3/src/ui-predicate-comparison-argument.vue
<template>
  <component
    :is="getArgumentTypeComponentById(predicate.operator.argumentType_id)"
    :value="predicate.argument"
    :predicate="predicate"
    @change="_setArgumentValue"
  />
</template>

<script>
export default {
  props: {
    predicate: {
      type: Object,
      required: true,
    },
  },
  inject: ["getArgumentTypeComponentById", "setArgumentValue"],
  methods: {
    _setArgumentValue(value) {
      this.setArgumentValue(this.predicate, value);
    },
  },
};
</script>
