// packages/ui-predicate-react/src/default-components/logical-types.js
import React from 'react';

export default function LogicalTypes({ predicate, columns, onChange }) {
  return (
    <select
      value={predicate.logic.logicalType_id}
      onChange={ev => onChange(ev.target.value)}
    >
      {columns.logicalTypes.map(logicalType => (
        <option key={logicalType.label} value={logicalType.logicalType_id}>
          {logicalType.label}
        </option>
      ))}
    </select>
  );
}

// packages/ui-predicate-vue3/src/default-components/logical-types.vue
<script setup>
defineEmits(['change']);

defineProps({
  predicate: {
    type: Object,
    required: true,
  },
  columns: {
    type: Object,
    required: true,
  },
});

</script>

<template>
  <select
  :value="predicate.logic.logicalType_id"
  @change="$emit('change', $event.target.value)">
    <option
    v-for="logicalType in columns.logicalTypes"
    :key="logicalType.label"
    :value="logicalType.logicalType_id">
      {{ logicalType.label }}
    </option>
  </select>
</template>
