// packages/ui-predicate-react/src/default-components/targets.js
import React from 'react';

export default function Targets({ predicate, columns, onChange }) {
  return (
    <select
      value={predicate.target.target_id}
      onChange={ev => onChange(ev.target.value)}
    >
      {columns.targets.map(target => (
        <option key={target.label} value={target.target_id}>
          {target.label}
        </option>
      ))}
    </select>
  );
}

// packages/ui-predicate-vue3/src/default-components/targets.vue
<script setup>
defineEmits(['change']);

defineProps({
  columns: {
    type: Object,
    required: true,
  },
  predicate: {
    type: Object,
    required: true,
  },
})
</script>

<template>
  <select
    :value="predicate.target.target_id"
    @change="$emit('change', $event.target.value)">
    <option
      v-for="target in columns.targets"
      :key="target.label"
      :value="target.target_id">{{target.label}}
    </option>
  </select>
</template>
