// packages/ui-predicate-react/src/components/default-components/Operators.js
import React from 'react';
import PropTypes from 'prop-types';

export default function Operators({ predicate, onChange }) {
  return (
    <select
      className="ui-predicate__operators"
      value={predicate.operator.operator_id}
      onChange={e => onChange(e.target.value)}
    >
      {predicate.target.$type.$operators.map(operator => {
        return (
          <option key={operator.label} value={operator.operator_id}>
            {operator.label}
          </option>
        );
      })}
    </select>
  );
}

Operators.propTypes = {
  predicate: PropTypes.object,
  columns: PropTypes.object,
  onChange: PropTypes.func,
};

// packages/ui-predicate-vue/src/default-components/operators.vue
<template>
    <select
        :value="predicate.operator.operator_id"
        @change="$emit('change', $event.target.value)">
        <option
            v-for="operator in predicate.target.$type.$operators"
            :key="operator.label"
            :value="operator.operator_id">{{operator.label}}
        </option>
    </select>
</template>

<script>
export default {
    props: {
        columns: {
            type: Object,
            required: true,
        },
        predicate: {
            type: Object,
            required: true,
        },
  },
}
</script>
