// packages/ui-predicate-vue3/src/ui-predicate-compound.vue
<template>
  <div class="ui-predicate__row--compound">
    <div class="ui-predicate__row">
      <div class="ui-predicate__col">
        <component
          class="ui-predicate__logic"
          v-if="predicate.logic"
          :is="getUIComponent(UITypes.LOGICAL_TYPES)"
          :predicate="predicate"
          :columns="columns"
          @change="changeLogic($event)"
        />
      </div>
      <div class="ui-predicate__col">
        <ui-predicate-options :predicate="predicate"></ui-predicate-options>
      </div>
    </div>
    <template v-for="(model, index) in predicate.predicates">
      <ui-predicate-compound
        v-if="model.$_type === 'CompoundPredicate'"
        :predicate="model"
        :key="index"
        :columns="columns">
      </ui-predicate-compound>
      <ui-predicate-comparison
        v-if="model.$_type === 'ComparisonPredicate'"
        :predicate="model"
        :key="index"
        :columns="columns">
      </ui-predicate-comparison>
    </template>
  </div>
</template>

<script setup>
import { inject } from "vue";

const props = defineProps({
  predicate: {
    type: Object,
    required: true,
  },
  columns: {
    type: Object,
    required: true,
  },
});


const setPredicateLogicalType_id = inject("setPredicateLogicalType_id");
const UITypes = inject("UITypes");
const getUIComponent = inject("getUIComponent");

const changeLogic = (logicalType_id) => setPredicateLogicalType_id(props.predicate, logicalType_id);
</script>

// packages/ui-predicate-react/src/components/UIPredicateCompound.js
import React from 'react';
import PropTypes from 'prop-types';
import { useUIPredicateContext } from '../hooks';
import { UIPredicateOptions, UIPredicateComparison } from './';

export function UIPredicateCompound({ predicate, columns }) {
  const {
    setPredicateLogicalType_id,
    UITypes,
    getUIComponent,
  } = useUIPredicateContext();

  const LogicalTypesComponent = getUIComponent(UITypes.LOGICAL_TYPES);
  return (
    <div className="ui-predicate__row--compound">
      <div className="ui-predicate__row">
        <div className="ui-predicate__col">
          {predicate.logic && (
            <LogicalTypesComponent
              predicate={predicate}
              columns={columns}
              onChange={logicalType_id => {
                setPredicateLogicalType_id(predicate, logicalType_id);
              }}
            />
          )}
        </div>
        <div className="ui-predicate__col">
          <UIPredicateOptions predicate={predicate} />
        </div>
      </div>
      {predicate.predicates.map((childPredicate, index) => {
        const ChildPredicateComponent = (() => {
          if (childPredicate.$_type === 'CompoundPredicate')
            return UIPredicateCompound;

          if (childPredicate.$_type === 'ComparisonPredicate')
            return UIPredicateComparison;

          return undefined;
        })();
        if (!ChildPredicateComponent) return null;

        return (
          <ChildPredicateComponent
            key={index}
            predicate={childPredicate}
            columns={columns}
          />
        );
      })}
    </div>
  );
}

UIPredicateCompound.propTypes = {
  predicate: PropTypes.object,
  columns: PropTypes.object,
};
