// packages/ui-predicate-vue/src/default-components/logical-types.vue
<template>
    <select
    :value="predicate.logic.logicalType_id"
    @change="$emit('change', $event.target.value)">
        <option
            v-for="logicalType in columns.logicalTypes"
            :key="logicalType.label"
            :value="logicalType.logicalType_id">{{logicalType.label}}
        </option>
    </select>
</template>

<script>
export default {
    props: {
        predicate: {
            type: Object,
            required: true,
        },
        columns: {
            type: Object,
            required: true,
        },
    }
}
</script>

// packages/ui-predicate-react/src/default-components/logical-types.js
import React from 'react';

export default function LogicalTypes({ predicate, columns, onChange }) {
  return (
    <select
      value={predicate.logic.logicalType_id}
      onChange={ev => onChange(ev.target.value)}
    >
      {columns.logicalTypes.map(logicalType => (
        <option key={logicalType.label} value={logicalType.logicalType_id}>
          {logicalType.label}
        </option>
      ))}
    </select>
  );
}
