// packages/ui-predicate-vue3/src/default-components/operators.vue
<script setup>
defineEmits(['change']);

defineProps({
  columns: {
    type: Object,
    required: true,
  },
  predicate: {
    type: Object,
    required: true,
  },
});

</script>

<template>
  <select
    :value="predicate.operator.operator_id"
    @change="$emit('change', $event.target.value)">
    <option
      v-for="operator in predicate.target.$type.$operators"
      :key="operator.label"
      :value="operator.operator_id">{{operator.label}}
    </option>
  </select>
</template>

// packages/ui-predicate-react/src/default-components/operators.js
import React from 'react';

export default function Operators({ predicate, onChange }) {
  return (
    <select
      value={predicate.operator.operator_id}
      onChange={ev => onChange(ev.target.value)}
    >
      {predicate.target.$type.$operators.map(operator => (
        <option key={operator.label} value={operator.operator_id}>
          {operator.label}
        </option>
      ))}
    </select>
  );
}
