// packages/ui-predicate-vue/src/ui-predicate-options.vue
<template>
  <div class="ui-predicate__options">
    <div class="ui-predicate__option">
      <component
        :is="getUIComponent(UITypes.PREDICATE_REMOVE)"
        @click.native="remove(predicate)"
        :predicate="predicate"
        :disabled="predicate.$canBeRemoved === false"
      />
    </div>
    <div class="ui-predicate__option">
      <component
        :is="getUIComponent(UITypes.PREDICATE_ADD)"
        @click.native="add(predicate)"
        :predicate="predicate"
        :is-in-add-compound-mode="isInAddCompoundMode"
      />
    </div>
  </div>
</template>

<script>
export default {
  name: 'ui-predicate-options',
  props: {
    predicate: {
      type: Object,
      required: true,
    },
  },
  inject: ['remove', 'add', 'getAddCompoundMode', 'UITypes', 'getUIComponent'],
  computed: {
    isInAddCompoundMode() {
      return this.getAddCompoundMode();
    },
  },
};
</script>

// packages/ui-predicate-react/src/ui-predicate-options.js
import React, { Component } from 'react';
import { UITypes } from 'ui-predicate-core';

class UIPredicateOptions extends Component {
  render() {
    const {
      predicate,
      remove,
      add,
      getUIComponent,
      getAddCompoundMode,
    } = this.props;
    const RemoveComponent = getUIComponent(UITypes.PREDICATE_REMOVE);
    const AddComponent = getUIComponent(UITypes.PREDICATE_ADD);

    return (
      <div className="ui-predicate__options">
        <div className="ui-predicate__option">
          <RemoveComponent
            {...this.props}
            onClick={() => remove(predicate)}
            predicate={predicate}
            disabled={predicate.$canBeRemoved === false}
          />
        </div>
        <div className="ui-predicate__option">
          <AddComponent
            {...this.props}
            onClick={() => add(predicate)}
            predicate={predicate}
            isInAddCompoundMode={getAddCompoundMode()}
          />
        </div>
      </div>
    );
  }
}

export default UIPredicateOptions;
