// packages/ui-predicate-vue3/src/ui-predicate-options.vue
<template>
  <div class="ui-predicate__options">
    <div class="ui-predicate__option">
      <component
        :is="getUIComponent(UITypes.PREDICATE_REMOVE)"
        :predicate="predicate"
        :disabled="predicate.$canBeRemoved === false"
        @click="remove(predicate)"
      />
    </div>
    <div class="ui-predicate__option">
      <component
        :is="getUIComponent(UITypes.PREDICATE_ADD)"
        :predicate="predicate"
        :is-in-add-compound-mode="isInAddCompoundMode"
        @click="add(predicate)"
      />
    </div>
  </div>
</template>

<script setup>
import { inject, computed } from "vue";

defineProps({
  predicate: {
    type: Object,
    required: true
  }
});

const remove = inject("remove");
const add = inject("add");
const getAddCompoundMode = inject("getAddCompoundMode");
const UITypes = inject("UITypes");
const getUIComponent = inject("getUIComponent");

const isInAddCompoundMode = computed(() => getAddCompoundMode());
</script>

// packages/ui-predicate-react/src/ui-predicate-options.js
import React, { Component } from 'react';
import { UITypes } from 'ui-predicate-core';

class UIPredicateOptions extends Component {
  render() {
    const {
      predicate,
      remove,
      add,
      getUIComponent,
      getAddCompoundMode,
    } = this.props;
    const RemoveComponent = getUIComponent(UITypes.PREDICATE_REMOVE);
    const AddComponent = getUIComponent(UITypes.PREDICATE_ADD);

    return (
      <div className="ui-predicate__options">
        <div className="ui-predicate__option">
          <RemoveComponent
            {...this.props}
            onClick={() => remove(predicate)}
            predicate={predicate}
            disabled={predicate.$canBeRemoved === false}
          />
        </div>
        <div className="ui-predicate__option">
          <AddComponent
            {...this.props}
            onClick={() => add(predicate)}
            predicate={predicate}
            isInAddCompoundMode={getAddCompoundMode()}
          />
        </div>
      </div>
    );
  }
}

export default UIPredicateOptions;
