// packages/ui-predicate-vue/src/ui-predicate-comparison.vue
<template>
  <div class="ui-predicate__row ui-predicate__row--comparison">
      <div class="ui-predicate__col">
        <component
          class="ui-predicate__targets"
          :is="getUIComponent(UITypes.TARGETS)"
          :columns="columns"
          :predicate="predicate"
          @change="changeTarget($event)"
        />
      </div>
      <div class="ui-predicate__col">
        <component
          class="ui-predicate__operators"
          :is="getUIComponent(UITypes.OPERATORS)"
          :columns="columns"
          :predicate="predicate"
          @change="changeOperator($event)"
        />
      </div>
      <div class="ui-predicate__col">
        <ui-predicate-comparison-argument
          class="ui-predicate__arguments"
          :predicate="predicate"
        />
      </div>
      <div class="ui-predicate__col">
        <ui-predicate-options :predicate="predicate" />
      </div>
    </div>
</template>

<script>
export default {
  name: 'ui-predicate-comparison',
  props: {
    predicate: {
      type: Object,
      required: true,
    },
    columns: {
      type: Object,
      required: true,
    },
  },
  inject: [
    'add',
    'setPredicateTarget_id',
    'setPredicateOperator_id',
    'UITypes',
    'getUIComponent',
  ],
  methods: {
    changeTarget(target_id) {
      this.setPredicateTarget_id(this.predicate, target_id);
    },
    changeOperator(operator_id) {
      this.setPredicateOperator_id(this.predicate, operator_id);
    },
  },
};
</script>

// packages/ui-predicate-react/src/ui-predicate-comparison.js
import React, { Component } from 'react';
import { UITypes } from 'ui-predicate-core';
import UIPredicateComparisonArgument from './ui-predicate-comparison-argument';
import UIPredicateOptions from './ui-predicate-options';

class UIPredicateComparison extends Component {
  constructor(props) {
    super(props);
    this.changeTarget = this.changeTarget.bind(this);
    this.changeOperator = this.changeOperator.bind(this);
  }

  changeTarget(target_id) {
    const { predicate } = this.props;
    this.props.setPredicateTarget_id(predicate, target_id);
  }

  changeOperator(operator_id) {
    const { predicate } = this.props;
    this.props.setPredicateOperator_id(predicate, operator_id);
  }

  render() {
    const { predicate, columns, getUIComponent } = this.props;

    const TargetsComponent = getUIComponent(UITypes.TARGETS);
    const OperatorsComponent = getUIComponent(UITypes.OPERATORS);

    return (
      <div className="ui-predicate__row ui-predicate__row--comparison">
        <div className="ui-predicate__col">
          <TargetsComponent
            {...this.props}
            className="ui-predicate__targets"
            columns={columns}
            predicate={predicate}
            onChange={target_id => this.changeTarget(target_id)}
          />
        </div>
        <div className="ui-predicate__col">
          <OperatorsComponent
            {...this.props}
            className="ui-predicate__operators"
            columns={columns}
            predicate={predicate}
            onChange={operator_id => this.changeOperator(operator_id)}
          />
        </div>
        <div className="ui-predicate__col">
          <UIPredicateComparisonArgument
            {...this.props}
            className="ui-predicate__arguments"
            predicate={predicate}
          />
        </div>
        <div className="ui-predicate__col">
          <UIPredicateOptions {...this.props} predicate={predicate} />
        </div>
      </div>
    );
  }
}

export default UIPredicateComparison;
