// packages/ui-predicate-react/src/ui-predicate-compound.js
import React, { Component } from 'react';
import { UITypes } from 'ui-predicate-core';
import UIPredicateComparison from './ui-predicate-comparison';
import UIPredicateOptions from './ui-predicate-options';

class UIPredicateCompound extends Component {
  constructor(props) {
    super(props);
    this.changeLogic = this.changeLogic.bind(this);
    this.renderPredicates = this.renderPredicates.bind(this);
  }

  changeLogic(logicalType_id) {
    this.props.setPredicateLogicalType_id(this.props.predicate, logicalType_id);
  }

  renderPredicates(predicates, columns) {
    return predicates.map((model, index) => {
      if (model.$_type === 'CompoundPredicate') {
        return (
          <UIPredicateCompound
            {...this.props}
            key={index}
            predicate={model}
            columns={columns}
          />
        );
      }
      if (model.$_type === 'ComparisonPredicate') {
        return (
          <UIPredicateComparison
            {...this.props}
            key={index}
            predicate={model}
            columns={columns}
          />
        );
      }
      return null;
    });
  }
  render() {
    const { predicate, columns, getUIComponent } = this.props;
    const LogicalTypesComponent = getUIComponent(UITypes.LOGICAL_TYPES);

    return (
      <div className="ui-predicate__row--compound">
        <div className="ui-predicate__row">
          <div className="ui-predicate__col">
            {Boolean(predicate.logic) && (
              <LogicalTypesComponent
                {...this.props}
                className="ui-predicate__logic"
                predicate={predicate}
                columns={columns}
                onChange={value => this.changeLogic(value)}
              />
            )}
          </div>
          <div className="ui-predicate__col">
            <UIPredicateOptions {...this.props} predicate={predicate} />
          </div>
        </div>
        {this.renderPredicates(predicate.predicates, columns)}
      </div>
    );
  }
}

export default UIPredicateCompound;

// packages/ui-predicate-vue/src/ui-predicate-compound.vue
<template>
    <div class="ui-predicate__row--compound">
      <div class="ui-predicate__row">
        <div class="ui-predicate__col">
          <component
            class="ui-predicate__logic"
            v-if="predicate.logic"
            :is="getUIComponent(UITypes.LOGICAL_TYPES)"
            :predicate="predicate"
            :columns="columns"
            @change="changeLogic($event)"
          />
        </div>
        <div class="ui-predicate__col">
          <ui-predicate-options :predicate="predicate"></ui-predicate-options>
        </div>
      </div>
      <template v-for="(model, index) in predicate.predicates">
        <ui-predicate-compound
          :key="index"
          v-if="model.$_type === 'CompoundPredicate'"
          :predicate="model"
          :columns="columns">
        </ui-predicate-compound>
        <ui-predicate-comparison
          :key="index"
          v-if="model.$_type === 'ComparisonPredicate'"
          :predicate="model"
          :columns="columns">
        </ui-predicate-comparison>
      </template>
    </div>
</template>

<script>
export default {
  name: 'ui-predicate-compound',
  props: {
    predicate: {
      type: Object,
      required: true,
    },
    columns: {
      type: Object,
      required: true,
    },
  },
  inject: ['add', 'setPredicateLogicalType_id', 'UITypes', 'getUIComponent'],
  methods: {
    changeLogic(logicalType_id) {
      this.setPredicateLogicalType_id(this.predicate, logicalType_id);
    },
  },
};
</script>
